typography_spectrum: 0.3944786449428648
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.4659881724510342
  lightness: 0.8750376203097403
  saturation: 0.9284286708571017
  rhythmicContrast: 0.6717305262573063
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6107327453792095
analytics:
  google: null
  facebook: null
  twitter: null
name: Boundaries
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
